### ISSUE TITLE
terminology

### ISSUE THREAD

**Issue by EddieTheEd** [spicata/mint-fresh-notes#1]
no one knows what the word thematic means

please fix seeing the word thematic really ruins the user experience

**>:(**

**Comment by spicata** [comment]
Ok, I will.

**Comment by EddieTheEd** [comment]
Love you ❤️

**Comment by spicata** [comment]
Should be changed now.

**Comment by EddieTheEd** [comment]
Love you ❤️

**Comment by spicata** [comment]
You too 🫀
